### ISSUE TITLE
验证码是4个方块？

### ISSUE THREAD

**Issue by zhaoker** [fsender/readguy#1]
esp8266 连上wifi,设置完成后，验证码出现 四个方块 ......Arduino IDE 编译，过程全部正常

**Comment by fsender** [comment]
你在配置引脚时 有没有配置按键的数量和按键的引脚? 如果配置了就按一下 屏幕上就会逐字显示验证码.
验证是为了避免配置之后按键不灵或者未正确配置就进入正式代码, 导致后续的硬件功能无法正常使用.
详见代码注释

**Comment by fsender** [comment]
由于历史原因, 这个库就是必须绑定一个按钮的, 即使你用不上这个按钮, 那就在程序的其他部分不用这个按钮. 设置一个按钮的引脚, 再在出现四个方块之后依次 点按 双击 三连击 长按按键, 按下之后屏幕会刷新出数字. 直到四个方块出现数字, 最后将屏幕上的验证数字输入到配网网页端就可以了.
如果你以后的程序不需要用到这个按键, 那就在网页配置好之后拆掉这颗按键.

**Comment by fsender** [comment]
由于历史原因, 这个库就是必须绑定一个按钮的, 即使你用不上这个按钮, 那就在程序的其他部分不用这个按钮. 设置一个按钮的引脚, 再在出现四个方块之后依次 点按 双击 三连击 长按按键, 按下之后屏幕会刷新出数字. 直到四个方块出现数字, 最后将屏幕上的验证数字输入到配网网页端就可以了.
如果你以后的程序不需要用到这个按键, 那就在网页配置好之后拆掉这颗按键.
